apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-alerts
  namespace: monitoring
spec:
  groups:
  - name: pod.rules
    rules:
    - alert: PodCrashing
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Pod crash looping"
        description: "Pod has restarted more than 3 times in the last 5 minutes."